#---------------------------------------------- eureka slave1 注册中心配置 ----------------------------------------------------
server:
  port: 18761

spring:
  application:
    name: hms-server-eureka # 应用名称
#  profiles: slave1 # 【eureka服务器集群 —— 节点1】，用于main方法启动的时候，用户需要输入的内容。标识启动的是哪一个eureka服务器；

eureka:
  instance:
    hostname: server.eureka.slave1.com # 服务所在主机（一般都是配置域名）；本地测试的话，需要在 host 文件中指定虚拟域名
  client:
    service-url:
      defaultZone: http://user:password@server.eureka.slave2.com:28761/eureka # eureka服务器的地址，互相进行监控，设置服务注册中心地址，指向另一个注册中心
    fetch-registry: false # 获取注册列表
    register-with-eureka: true # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息


# 注意下面是三个横杠：在单一文件中，可用连续三个连字号（---）区分多个文件（节省多个yml文件的配置，在一个yml文件中就可配置）。

--- #---------------------------------------- eureka slave2 注册中心配置 ----------------------------------------------------
server:
  port: 28761

spring:
  application:
    name: hms-server-eureka # 应用名称
  profiles: slave2 # 【eureka服务器集群 —— 节点2】 用于main方法启动的时候，用户需要输入的内容。标识启动的是哪一个eureka服务器；

eureka:
  instance:
    hostname: server.eureka.slave2.com # 服务所在主机（一般都是配置域名；本地测试的话，需要在 host 文件中指定虚拟域名
  client:
    service-url:
      defaultZone: http://server.eureka.slave1.com:18761/eureka # eureka服务器的地址
    fetch-registry: false # 获取注册列表
    register-with-eureka: true # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息

#添加用户验证
security:
  basic:
    enabled: true           # 开启基于HTTP basic的认证
  user:
    name: user              # 配置登录的账号是user
    password: password   # 配置登录的密码是password
